server:
  port: 8080

toggle:
  taskEnable: false

account:
  #是否启动时重置管理员权限
  reset-admin-perms: false
  enable-captcha: true
  allow-platform-user-register: false
  allow-app-user-register: true
  check-reset-password: true

crud-plus:
  features:
     - eav
#     - saas
     - tag

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    converters:
      preferred-json-mapper: fastjson
  mail:
    host: smtp.126.com
    port: 25
    username: jiajiajia5000@126.com
    password: CFERNTQPRZYHBRXO
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  resources:
    static-locations: file:/attachments/
  # rabbitMQ配置
  rabbitmq:
    host: 202.63.172.178
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000
#github登录模块配置
#配置类 com.jfeat.am.uaas.github.model.GitHubSetting
GitHub:
  client-id: 9256baf36c5aa289d2d2
  client-secret: 8fb3c6bb0ef512c2cd5b4be657206679676a64e0

###################  jwt配置  ###################
jwt:
  encoded-key: L7A/6zARSkK1j7Vd5SDD9pSSqZlqF7mAhiOgRbgv9Smce6tf4cJnvKOjtKPxNNnWQj+2lQEScm3XIUjhW+YVZg==
  normal-encoded-key: bm9ybWFsLWVuY29kZWQta2V5
  ttl-millis: 604800000
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath*:com/jfeat/**/mapping/*.xml
  typeAliasesPackage: com.jfeat.**.model
  global-config:
    id-type: 2  #0:数据库ID自增   1:用户输入id   2:全局唯一id(IdWorker)   3:全局唯一ID(uuid)  4: 该类型为未设置主键类型(none)
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 1
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

# 短信配置
sms:
  nameless:
    base-url: http://47.105.121.66:8001/sms # 根路径
    username: 150089 # 服务用户名
    password: oAhA9YqDaBR1 # 密码
    apis:
      oneOnOne:
        url: /api/sendMessageOne
      mass:
        url: /api/sendMessageMass
    templates: # 模版列表
      alterPw: # 模版key
        name: 修改密码验证码
        code: SMS_138535094
        content: 【新质数创】尊敬的用户，您好！您正在修改新质数创党建一体机登录密码，验证码%s。为保护账号安全，请勿泄漏或转发他人。
      register:
        name: 用户注册验证码
        code: SMS_138535095
        content: 【新质数创】验证码%s，尊敬的用户，您好！您正在进行新质数创党建一体机账号注册操作，该验证码5分钟内有效，为保护账号安全，请勿泄漏或转发他人。
      loginUnusual:
        name: 登录异常验证码
        code: SMS_138535096
        content: 【新质数创】尊敬的用户，您好！您的新质数创党建一体机账号正在一个新设备上登录，验证码%s。该验证码5分钟Alter内有效，为保护账号安全，请勿泄漏或转发他人。
      loginCheck:
        name: 登录确认验证码
        code: SMS_138535097
        content: 【新质数创】尊敬的用户，您好！您正在登录新质数创党建一体机账号，验证码%s。该验证码5分钟内有效，为保护账号安全，请勿泄漏或转发他人。
      authentication:
        name: 身份验证验证码
        code: SMS_138535098
        content: 【新质数创】验证码%s。尊敬的用户，您好！您正在进行身份验证，验证码提供他人可能导致账号被盗，请勿转发或泄漏。
      infoUpdate:
        name: 信息变更验证码
        code: SMS_138535093
        content: 【新质数创】尊敬的用户，您好！您正在进行新质数创党建一体机账号信息变更操作，验证码%s。该验证码5分钟内有效，为保护账号安全，请勿泄漏或转发他人。
